sudo: false

language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install tox
  - pip install tox-travis
  - pip install coveralls

script:
  - tox

after_success: coveralls
